server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: nbi-mns-example
  profiles:
    active: dev

# NBI MnS API Configuration
nbi:
  mns:
    fault-mns-enabled: true
    perf-mns-enabled: true
    base-path: /api/v1
    api-documentation-enabled: true

# Logging configuration
logging:
  level:
    com.example.ems: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  show-actuator: false
